### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ralphtheninja** [Level/iterator-stream#17]
- [x] remove `v2` branch
- [x] close https://github.com/Level/iterator-stream/issues/14
- [x] fix https://github.com/Level/iterator-stream/issues/2
- [x] release `level-iterator-stream@2.0.0`
- [x] close https://github.com/Level/levelup/issues/453
